### ISSUE TITLE
Where to install. 

### ISSUE THREAD

**Issue by sohail042414** [yii2mod/base#12]
Not clear where to install this??
1-Install yii2 basic app first using composer, and then install your app (base) within that basic app?? 
If I run the command given here in documentation, it adds a folder within basic app named application.
2-Is your base app complete package having everthing in it?? If I look into code it does not include vendor directory. (means have not framework).  It has all other directories that make it complete app. 
3- other option is to set up  basic app, download your app, and merge things and configure???

**Comment by igor-chepurnoi** [comment]
1. composer global require "fxp/composer-asset-plugin:^1.2.0"
2. composer create-project --prefer-dist --stability=dev yii2mod/base yii2-base
3. Create a new database and adjust the components['db'] configuration in config/common-local.php accordingly.
4. php yii migrate
5. php yii rbac/migrate

Also you need to configure your apache or nginx virtual host.

**Comment by igor-chepurnoi** [comment]
Also you can install app via docker:
See this link - https://github.com/yii2mod/base#installing-using-docker

**Comment by igor-chepurnoi** [comment]
All installation steps taken from [yii2/basic](https://github.com/yiisoft/yii2-app-basic) except migration execution
