### ISSUE TITLE
theme manager

### ISSUE THREAD

**Issue by masihfathi** [yii2mod/base#34]
thanks for your extensions. is it possible adding an extension to manage theme in yii2 easily for exmple changing template from admin panel or sth similar to cms theme manager.  it is really good and make yii2 and your extension make sense and amazing? this is really good cause adding an extra extension in your extension is really easy and make development of new features in the project faster which dont need to use  cms and ... for regular features which take time to write from starting point.

**Comment by igor-chepurnoi** [comment]
Hi, thanks for your issue. Interesting purpose, but now I don't have enough time for this feature. Maybe later  :)
