### ISSUE TITLE
error migrating up 

### ISSUE THREAD

**Issue by masihfathi** [yii2mod/base#36]
i update my project with composer update and yii version update to 2.0.12 and yii2mod/yii2-user update to version 2.1, now when i update migration with "php yii migrate --migrationPath=@vendor/yii2mod/yii2-user/migrations" , i got the below error:
`PHP Warning 'yii\base\ErrorException' with message 'strncmp() expects parameter 1 to be string, array given'
in /var/www/html/test/vendor/yiisoft/yii2/BaseYii.php:133
Stack trace:
#0 [internal function]: yii\base\ErrorHandler->handleError(2, 'strncmp() expec...', '/var/www/html/test', 133, Array)
`

**Comment by tokiaquino** [comment]
See #35
