### ISSUE TITLE
requirements

### ISSUE THREAD

**Issue by masihfathi** [yii2mod/base#40]
thanks for your great extension i have a question about requirements, dose this extension work in php 7.0?
and another question can i use this extension in production? cause in production we can't change php version all time's for example if php 7.2 finally released it takes time to update php version of server and sometimes in production it is not possible to change php version frequently. yii2 will require php 7 in the yii 2.1 but you all time update php version. how we can sustain the project when you update php versions all time?

**Comment by igor-chepurnoi** [comment]
Hi, for this template I set minimum php version to 7.1 and I update php every two months only for Docker container. You can use this template for production, of course. But in most of all packages in yii2mod, min. php version = 7.1

**Comment by masihfathi** [comment]
thanks for your answer.
