### ISSUE TITLE
have problem to run the app 

### ISSUE THREAD

**Issue by mamadza** [yii2mod/base#42]
hi , I have problem to run the app I did all of the CONFIGURATION setting in 

but I don't know what I am do in step 4 :
 
4- Set document root of your web server to /path/to/application/web/ folder.

If I enter  http://localhost/base-app/web/      -> then the site/index loaded but when I click In another link or I want to entire in admin module this redirect me to  http://localhost/dashboard/

![image](https://user-images.githubusercontent.com/12842935/32430765-e421dad8-c2e5-11e7-9db0-a627c42fa0ab.png)

after click 

![image](https://user-images.githubusercontent.com/12842935/32430787-f97c9864-c2e5-11e7-8dc2-30b7cd06e500.png)

what can I do to solve this problem?

**Comment by masihfathi** [comment]
you can solve the problem by using php yii serve in the root of project. or in the the production change the root of e.x apache to web folder.

**Comment by mamadza** [comment]
tank you
