### ISSUE TITLE
User, CMS / Column Names Mismatch

### ISSUE THREAD

**Issue by juppwerner** [yii2mod/base#46]
The installation migration produces column names with dashes like created_at, auth_key,

The data in tests/_data reflects column names in camel case.

I changed the column names in the _data scripts to the ones using dashes; then the `yii fixture "*"` script runs.

But then opening web/index.php/admin throws an error on "Getting unknown property: app\models\UserModel::createdAt".

Regards
Joachim

**Comment by igor-chepurnoi** [comment]
Please see my response in this (issue)[https://github.com/yii2mod/base/issues/45]
