### ISSUE TITLE
Installation migrate causing SQL error

### ISSUE THREAD

**Issue by GauthamR** [yii2mod/base#48]
I am working on my local machine using a MAMP setup which has multiple other Yii2 projects running.
Created new project with yii2mod/base, initiated the project, updated db config and then running - _php yii migrate_

I get an SQL error after about 4-5 minutes of running the command
**Exception 'yii\db\Exception' with message 'SQLSTATE[HY000] [2006] MySQL server has gone away'**

Below is log after running the command - 

`Yii Migration Tool (based on Yii v2.0.15.1)`

`Exception 'yii\db\Exception' with message 'SQLSTATE[HY000] [2006] MySQL server has gone away' in /Applications/MAMP/htdocs/ryberg/vendor/yiisoft/yii2/db/Connection.php:624`

`Stack trace:`
`#0 /Applications/MAMP/htdocs/ryberg/vendor/yiisoft/yii2/db/Connection.php(996): yii\db\Connection->open()`
`#1 /Applications/MAMP/htdocs/ryberg/vendor/yiisoft/yii2/db/Connection.php(983): yii\db\Connection->getMasterPdo()`
`#2 /Applications/MAMP/htdocs/ryberg/vendor/yiisoft/yii2/db/Command.php(253): yii\db\Connection->getSlavePdo()`
`#3 /Applications/MAMP/htdocs/ryberg/vendor/yiisoft/yii2/db/Command.php(1143): yii\db\Command->prepare(true)`
`#4 /Applications/MAMP/htdocs/ryberg/vendor/yiisoft/yii2/db/Command.php(399): yii\db\Command->queryInternal('fetchAll', NULL)`
`#5 /Applications/MAMP/htdocs/ryberg/vendor/yiisoft/yii2/db/mysql/Schema.php(312): yii\db\Command->queryAll()`
`#6 /Applications/MAMP/htdocs/ryberg/vendor/yiisoft/yii2/db/mysql/Schema.php(125): yii\db\mysql\Schema->findColumns(Object(yii\db\TableSchema))`
`#7 /Applications/MAMP/htdocs/ryberg/vendor/yiisoft/yii2/db/Schema.php(744): yii\db\mysql\Schema->loadTableSchema('migration')`
`#8 /Applications/MAMP/htdocs/ryberg/vendor/yiisoft/yii2/db/Schema.php(194): yii\db\Schema->getTableMetadata('{{%migration}}', 'schema', true)`
`#9 /Applications/MAMP/htdocs/ryberg/vendor/yiisoft/yii2/console/controllers/MigrateController.php(210): yii\db\Schema->getTableSchema('{{%migration}}', true)`
`#10 /Applications/MAMP/htdocs/ryberg/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(875): yii\console\controllers\MigrateController->getMigrationHistory(NULL)`
`#11 /Applications/MAMP/htdocs/ryberg/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(166): yii\console\controllers\BaseMigrateController->getNewMigrations()`
`#12 [internal function]: yii\console\controllers\BaseMigrateController->actionUp(0)`
`#13 /Applications/MAMP/htdocs/ryberg/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)`
`#14 /Applications/MAMP/htdocs/ryberg/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)`
`#15 /Applications/MAMP/htdocs/ryberg/vendor/yiisoft/yii2/console/Controller.php(148): yii\base\Controller->runAction('', Array)`
`#16 /Applications/MAMP/htdocs/ryberg/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('', Array)`
`#17 /Applications/MAMP/htdocs/ryberg/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('migrate', Array)`
`#18 /Applications/MAMP/htdocs/ryberg/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction('migrate', Array)`
`#19 /Applications/MAMP/htdocs/ryberg/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(yii\console\Request))`
`#20 /Applications/MAMP/htdocs/ryberg/yii(25): yii\base\Application->run()`
`#21 {main}`

Any chance I can get some help resolving this.

**Comment by igor-chepurnoi** [comment]
You can try to install this template with Docker. I can't reproduce this issue with docker.
